enforce_https: true
ignore_urls:
  - https://fonts.googleapis.com/
  - https://fonts.gstatic.com/
  - https://twitter.com/
  - https://twitter.com/username/
  - /twitter.com/intent/tweet/
  - https://linkedin.com/
  - https://www.linkedin.com/
  - https://www.linkedin.com/in/shivanshu-sharma-2302/
  - /http:\/\/localhost:4000\//
  - /http:\/\/127.0.0.1\//
  - /http:\/\/0.0.0.0\//
  - /archives/
  - /about/
empty_href_ignore: true
alt_ignore: true
ignore_elements:
  - a[class="site-title"]
  - a[class="footer-link"]
  - a[class="nav-link"]
  - a[class="social-link"]
ignore_status_codes:
  - 0
  - 400
  - 999
