ignore_urls:
  - https://fonts.googleapis.com
  - https://fonts.gstatic.com
  - https://twitter.com/
  - https://twitter.com/username
  - https://twitter.com/intent/tweet
  - https://linkedin.com/
  - https://www.linkedin.com/
  - /archives/
  - /about/
