# Full _config.yml to restore previous state
# The Site Configuration

theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Kolkata
title: Shivanshu Sharma
tagline: Welcome to my space
description: A portfolio site built by Shivanshu
url: https://uhsnavihs23.github.io/
github:
  username: uhsnavihs23
facebook:
  username: shivanshu.sharma.7737
linkedin:
  username: shivanshu-sharma-2302
social:
  name: Shivanshu Sharma
  email: shivanshu.sharma0023@gmail.com
  links:
    - https://twitter.com/username
    - https://github.com/uhsnavihs23
    - https://www.linkedin.com/in/shivanshu-sharma-2302/
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:
include:
  - assets/js
  - assets/projects
  - assets/files
  - projects
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:
pageviews:
  provider:
theme_mode:
cdn:
avatar: https://media.licdn.com/dms/image/v2/D5603AQF3OZdvlSZDhw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1730741353453?e=1751500800&v=beta&t=DktXAeILjBAm5KuLmgJeMSujkaFZIMySDppOsJNLhH8
social_preview_image:
toc: true
sidebar:
  home: true
  home_label: Home
  categories: false
  tags: false
  archives: false
  timeline: true
  post: false
comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo: uhsnavihs23/uhsnavihs23.github.io
    issue_term: pathname
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang: en_US
    reactions_enabled:
assets:
  self_host:
    enabled:
    env:
  css:
    - /assets/css/timeline.css
  js:
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
force_https: true
paginate: 10
navbar:
  - title: News
    url: /2025/05/11/news/
  - title: Projects
    url: /
  - title: About
    url: /about/
  - title: Timeline
    url: /timeline/
baseurl: ""
kramdown:
  footnote_backlink: "↩︎"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections:
  tabs:
    output: true
    sort_by: order
  projects:
    output: true
    permalink: /projects/:name/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: false
      categories: project # String to avoid YAML error
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
