theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Kolkata
url: "https://uhsnavihs23.github.io"
baseurl: ""
title: " "
author:
  name: Shivanshu Sharma
  url: "https://uhsnavihs23.github.io"
tagline: " "
description: Portfolio
github:
  username: uhsnavihs23
linkedin:
  username: shivanshu-sharma-2302
social:
  name: Shivanshu Sharma
  email: shivanshu.sharma0023@gmail.com
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:
pageviews:
  provider:
theme_mode:
cdn:
avatar: https://avatars.githubusercontent.com/u/67822353?v=4
social_preview_image:
toc: false
sidebar:
  nav: main
  home: true
  home_label: Home
  categories: false
  tags: false
  archives: true
  timeline: true
  post: false
comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo: uhsnavihs23/uhsnavihs23.github.io
    issue_term: pathname
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang: en_US
    reactions_enabled:
assets:
  self_host:
    enabled:
    env:
  css:
    - /assets/css/timeline.css
    - /assets/css/custom.scss
  js:
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
force_https: true
paginate: 10
kramdown:
  footnote_backlink: "↩︎"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections:
  data-analyst:
    output: true
    permalink: /projects/data-analyst-projects/:title/
  tabs:
    output: true
    sort_by: order
  projects:
    output: true
    permalink: /projects/:name/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: false
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: ""
    values:
      layout: default
sass:
  sass_dir: assets/css
  style: compressed
compress_html:
  enabled: false
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
include:
  - _includes/post-meta.html
exclude:
  - _site
  - .jekyll-cache
  - _site/_includes
  - assets/feed.xml
  - build.log
share:
  copy_link: false
